version: '3'
services:
  web:
    build: ./docker/web/
    container_name: "web"
    volumes:  
      - ./src/:/var/www/html/
    depends_on:
      - mysql
      - s3
    ports:
      - "8080:80"
    tty: true

  mysql:
    build: ./docker/mysql
    container_name: "mysql"
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/storage/data/mysql:/var/lib/mysql

  s3:
    build: ./docker/s3
    container_name: "s3"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/storage/data/s3:/export
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
